#!/bin/bash
#    I saved this as 'screen_backtick_battery'
# 2018-12-29: generate a number for a backtick command in screen, just
# the current battery percentage.
if [ -d /sys/class/power_supply/BAT?/ ]
then
    cat /sys/class/power_supply/BAT?/capacity
fi
